### ISSUE TITLE
messages and Input field UI issue

### ISSUE THREAD

**Issue by NomanGul** [rehan-sattar/slack-clone-react#1]
whenever the user sends some message It is going under the Input field section and I'm unable to view it properly:

![image](https://user-images.githubusercontent.com/39244918/78457768-11a74b00-76c6-11ea-9a1c-209f93767b89.png)

Maybe this issue only raising on some specific devices/screen-sizes...

**Comment by NomanGul** [comment]
also, I'm unable to scroll inside the user's section and there are some users under there:

![image](https://user-images.githubusercontent.com/39244918/78457835-92fedd80-76c6-11ea-829b-03d3ec792986.png)

**Comment by rehan-sattar** [comment]
Thank you so much for highlighting the issues. It would be good if you separate the Side bar issue into a separate issue. In this way we can track this one as well.

**Comment by rehan-sattar** [comment]
@NomanGul I have possibly tried one solution for it. Please test it now and advice if it sounds good to you.

**Comment by NomanGul** [comment]
yes, it's working fine now! 💜
