### ISSUE TITLE
users section UI issue

### ISSUE THREAD

**Issue by NomanGul** [rehan-sattar/slack-clone-react#2]
I'm unable to scroll inside the user's section and there are some users under there:

![image](https://user-images.githubusercontent.com/39244918/78457835-92fedd80-76c6-11ea-829b-03d3ec792986.png)

**Comment by rehan-sattar** [comment]
Thank you so much @NomanGul :heart:

**Comment by rehan-sattar** [comment]
@NomanGul  issue is fixed. Please test it once and let me know if it's working fine :smiley:

**Comment by NomanGul** [comment]
fixed! Thanks 🚀
